### ISSUE TITLE
Research Concerns: Define the evaluation procedure of the tool

### ISSUE THREAD

**Issue by fesiib** [temirrr/Priora#6]
1) What are the alternatives to our algorithm?
- Test Order Randomizer
- Forward and Backward order 
- (Optional) Greedy algorithm order

2) What are the objectives given to the NSGA-II algorithm? What is the fitness function? @kunduzb17 
- Failure/Success
- Execution time
- Memory allocated
- Maximum time interval `t_max`

3) How will we evaluate the effectiveness of our tool (i.e compare with other methods), in terms of what variables will we consider?
- `ttf` - time to first failure 
- `faf = foundAnyFailure/allExecutions` over all testing procedure

Feel free to add questions...

**Comment by amanzholov8** [comment]
I guess we also wanted to implement a simple greedy algorithm to compare NSGA with. One concern is that getting priorities through NSGA might be slow
